=== shel1ghost/Web-Technology/xml/companies_07/company.dtd
<!ELEMENT companies (company+)>
<!ELEMENT company (cname,staffs,address)>
<!ELEMENT cname (#PCDATA)>
<!ELEMENT staffs (staff+)>
<!ELEMENT staff (name,email,post,salary,join_date)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT post (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT join_date (#PCDATA)>
<!ELEMENT address (city,state)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ATTLIST company regno CDATA #REQUIRED>
<!ATTLIST address postalcode CDATA #REQUIRED>
<!ATTLIST join_date type (ad|bs) "ad">

=== shel1ghost/Web-Technology/xml/companies_07/company.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE companies SYSTEM "/home/astra/Desktop/study/web_xml/xml/companies_07/company.dtd">
<companies>
<company regno="6545">
  <cname>KMC</cname>
  <staffs>
    <staff>
      <name>Ranju</name>
      <email>info@test.com</email>
      <post>Manager</post>
      <salary>954545</salary>
      <join_date type="ad">2020-03-06</join_date>
    </staff>
    <staff>
      <name>Rita</name>
      <email>info@rita.com</email>
      <post>Helper</post>
      <salary>45000</salary>
      <join_date type="ad">2015-03-06</join_date>
    </staff>
  </staffs>
  <address postalcode="44600">
    <city>kathmandu</city>
    <state>Bagmati</state>
  </address>
  </company>
  <company regno="6545">
  <cname>RNMC</cname>
  <staffs>
    <staff>
      <name>Raman</name>
      <email>info@raman.com</email>
      <post>Manager</post>
      <salary>78000</salary>
      <join_date type="bs">2068-03-06</join_date>
    </staff>
    <staff>
      <name>Jamuna</name>
      <email>info@jamuna.com</email>
      <post>Helper</post>
      <salary>45000</salary>
      <join_date type="ad">2018-03-06</join_date>
    </staff>
  </staffs>
  <address postalcode="44600">
    <city>kathmandu</city>
    <state>Bagmati</state>
  </address>
  </company>
  </companies>
