<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students [
    <!ELEMENT students (student+)>
    <!ELEMENT student (name, phone, email, college, program, duration)>
    <!ATTLIST student id CDATA #REQUIRED> 
    <!ELEMENT name (first, middle?, last)>
    <!ATTLIST name title (mr | ms) #REQUIRED>
    <!ELEMENT first (#PCDATA)>
    <!ELEMENT middle (#PCDATA)>
    <!ELEMENT last (#PCDATA)>
    <!ELEMENT phone (#PCDATA)>
    <!ATTLIST phone type CDATA #REQUIRED>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT college (cname, address, website)>
    <!ATTLIST college id CDATA #REQUIRED>
    <!ELEMENT cname (#PCDATA)>
    <!ELEMENT address (#PCDATA)>
    <!ELEMENT website (#PCDATA)>
    <!ELEMENT program (#PCDATA)>
    <!ATTLIST program type CDATA #REQUIRED>
    <!ELEMENT duration (#PCDATA)>

]>
<students>
    <student id="01">
        <name title="mr">
            <first>Anup</first>
            <last>Gautam</last>
        </name>
        <phone type="work">9808085221</phone>
        <email>anup@gmail.com</email>
        <college id="22">
            <cname>Pascal National Collge</cname>
            <address>Satdobato</address>
            <website>www.pascalcollege.edu.np</website>
        </college>
        <program type="semester">BCA</program>
        <duration>4 years</duration>
    </student>
</students>